# Generated by Django 4.2.4 on 2023-08-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, verbose_name="@")),
                ("phone", models.CharField(max_length=17)),
                ("subject", models.CharField(max_length=255)),
                ("msg", models.CharField(max_length=255)),
            ],
        ),
    ]
